"""initial schema

Revision ID: a5ac5e9fdd48
Revises:
Create Date: 2026-05-14 16:56:36.278005

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5ac5e9fdd48"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before clinical_document.embedding is created. The
    # docker-compose initdb script also does this; repeating it here makes the
    # migration self-contained against any fresh database.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resource_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patient",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("given_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("family_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fhir_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patient_external_id"), "patient", ["external_id"], unique=False)
    op.create_table(
        "encounter",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("period_end", sa.DateTime(), nullable=True),
        sa.Column("class_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fhir_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_encounter_patient_id"), "encounter", ["patient_id"], unique=False)
    op.create_table(
        "clinical_document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("document_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("authored_on", sa.DateTime(), nullable=False),
        sa.Column("author_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author_role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("raw_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fhir_document_reference", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "fhir_clinical_impression", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounter.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_document_content_hash"),
        "clinical_document",
        ["content_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_clinical_document_encounter_id"),
        "clinical_document",
        ["encounter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_document_external_id"), "clinical_document", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_document_patient_id"), "clinical_document", ["patient_id"], unique=False
    )
    # Full-text search over the document body. A GENERATED column stays in sync
    # with raw_text automatically — no trigger, no application-side maintenance.
    # GIN-indexed for fast @@ queries (Phase 3 keyword retrieval).
    op.execute(
        "ALTER TABLE clinical_document "
        "ADD COLUMN fts tsvector "
        "GENERATED ALWAYS AS (to_tsvector('english', raw_text)) STORED"
    )
    op.create_index(
        "ix_clinical_document_fts", "clinical_document", ["fts"], postgresql_using="gin"
    )
    op.create_table(
        "asam_evidence",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("subdimension", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("snippet", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["clinical_document.id"],
        ),
        sa.PrimaryKeyConstraint("document_id", "dimension", "char_start"),
    )
    op.create_table(
        "extracted_observation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("code_system", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value_quantity", sa.Float(), nullable=True),
        sa.Column("value_string", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("extraction_method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["clinical_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extracted_observation_document_id"),
        "extracted_observation",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "tjc_coverage",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("ep_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("evidence_document_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_char_start", sa.Integer(), nullable=True),
        sa.Column("evidence_char_end", sa.Integer(), nullable=True),
        sa.Column("rationale", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_document_id"],
            ["clinical_document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.id"],
        ),
        sa.PrimaryKeyConstraint("patient_id", "ep_code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tjc_coverage")
    op.drop_index(op.f("ix_extracted_observation_document_id"), table_name="extracted_observation")
    op.drop_table("extracted_observation")
    op.drop_table("asam_evidence")
    op.drop_index(op.f("ix_clinical_document_patient_id"), table_name="clinical_document")
    op.drop_index(op.f("ix_clinical_document_external_id"), table_name="clinical_document")
    op.drop_index(op.f("ix_clinical_document_encounter_id"), table_name="clinical_document")
    op.drop_index(op.f("ix_clinical_document_content_hash"), table_name="clinical_document")
    op.drop_index("ix_clinical_document_fts", table_name="clinical_document")
    op.drop_table("clinical_document")
    op.drop_index(op.f("ix_encounter_patient_id"), table_name="encounter")
    op.drop_table("encounter")
    op.drop_index(op.f("ix_patient_external_id"), table_name="patient")
    op.drop_table("patient")
    op.drop_table("audit_event")
    # ### end Alembic commands ###
